"""Selector bias audit for rubric v1.

Question: does rubric v1 structurally favour leakage/recovery (LEAK) problems over
other archetypes (OTHER)? Uses the v1 weights unchanged. Scores for the 10 v1
survivors are copied verbatim from ../scores.csv; the 19 killed candidates were
scored retrospectively against the same v1 anchors (same analyst — a stated
limitation). C26 (energy waste) is M7 physical waste, so it is OTHER.
"""
import csv, random, statistics as st, pathlib, itertools
here = pathlib.Path(__file__).parent
D = ["SEV","FREQ","MEAS","ACC","TTP","SOLV","REP","URG","IMPL","RISK","SAT","COMP","AIL","PIND","LEARN","MOAT"]
W = dict(SEV=9,FREQ=6,MEAS=10,ACC=9,TTP=9,SOLV=7,REP=6,URG=9,IMPL=5,RISK=6,SAT=6,COMP=5,AIL=3,PIND=2,LEARN=4,MOAT=4)
PROOF = ["MEAS","TTP","ACC","IMPL"]            # "proof mechanics" cluster
rows = list(csv.DictReader(open(here/"v1_all_candidates.csv")))
for r in rows:
    for d in D: r[d] = int(r[d])
def score(r, w): return 100*sum(r[d]*w[d] for d in D)/(5*sum(w.values()))
L = [r for r in rows if r["group"]=="LEAK"]; O = [r for r in rows if r["group"]=="OTHER"]
out = []
p = out.append
p(f"n LEAK={len(L)}, n OTHER={len(O)}\n")

# 1. group means + permutation test
def gap(w, a=L, b=O): return st.mean(score(r,w) for r in a) - st.mean(score(r,w) for r in b)
g = gap(W)
random.seed(1); allr = rows[:]; ge = 0; N = 20000
for _ in range(N):
    random.shuffle(allr); a, b = allr[:len(L)], allr[len(L):]
    if gap(W, a, b) >= g: ge += 1
p(f"## 1. Mean v1 score\nLEAK {st.mean(score(r,W) for r in L):.1f} vs OTHER {st.mean(score(r,W) for r in O):.1f}; gap {g:+.1f} points; one-sided permutation p = {ge/N:.3f} ({N} shuffles)\n")

# 2. per-dimension decomposition of the gap
p("## 2. Where the gap comes from (weighted contribution, points of the 0-100 score)\n\n| dim | weight | mean LEAK | mean OTHER | contribution |\n|---|---|---|---|---|")
tot = 5*sum(W.values()); contrib = {}
for d in D:
    ml, mo = st.mean(r[d] for r in L), st.mean(r[d] for r in O)
    contrib[d] = 100*W[d]*(ml-mo)/tot
for d in sorted(D, key=lambda d: -contrib[d]):
    p(f"| {d} | {W[d]} | {st.mean(r[d] for r in L):.2f} | {st.mean(r[d] for r in O):.2f} | {contrib[d]:+.2f} |")
pc = sum(contrib[d] for d in PROOF); mc = contrib["MEAS"]
p(f"\nProof-mechanics cluster {PROOF} contributes {pc:+.2f} of the {g:+.2f} gap; MEAS alone {mc:+.2f}. All other dimensions together: {g-pc:+.2f}.\n")

# 3. counterfactual weight sets
sets = {
 "v1": W,
 "MEAS=0": {**W, "MEAS":0},
 "proof cluster=0": {**W, **{d:0 for d in PROOF}},
 "proof cluster halved": {**W, **{d:W[d]/2 for d in PROOF}},
 "equal": {d:1 for d in D},
}
p("## 3. Counterfactual weights: gap and top-4 composition\n\n| weight set | gap LEAK-OTHER | top 4 | LEAK in top 4 |\n|---|---|---|---|")
for n, w in sets.items():
    top = sorted(rows, key=lambda r: -score(r,w))[:4]
    p(f"| {n} | {gap(w):+.1f} | {', '.join(r['id'] for r in top)} | {sum(r['group']=='LEAK' for r in top)} |")

# 4. Monte Carlo over random weights (Dirichlet(1) = uniform on simplex)
random.seed(7); K = 20000; cnt = [0]*5; gaps = []
for _ in range(K):
    x = [random.expovariate(1) for _ in D]; w = dict(zip(D, x))
    top = sorted(rows, key=lambda r: -score(r,w))[:4]
    cnt[sum(r['group']=='LEAK' for r in top)] += 1; gaps.append(gap(w))
base = len(L)/len(rows)
p(f"\n## 4. Random weights (Dirichlet(1), {K} draws)\nLEAK share of all candidates = {base:.2f}, so a neutral selector puts ~{4*base:.1f} LEAK in a top 4.\nDistribution of #LEAK in top 4: " + ", ".join(f"{i}: {c/K:.1%}" for i,c in enumerate(cnt)))
p(f"Gap LEAK-OTHER > 0 in {sum(x>0 for x in gaps)/K:.1%} of draws; median gap {st.median(gaps):+.1f}.\n")

# 5. anchor bias: MEAS scores by group
p("## 5. Anchor check: MEAS score distribution\n")
for grp, rr in (("LEAK", L), ("OTHER", O)):
    p(f"- {grp}: MEAS=5 in {sum(r['MEAS']==5 for r in rr)}/{len(rr)}; mean {st.mean(r['MEAS'] for r in rr):.2f}")
(here/"audit_results.md").write_text("# v1 selector bias audit — generated by audit.py\n\n" + "\n".join(out) + "\n")
print("\n".join(out))
