"""Archetype coverage test: primary/secondary counts per archetype, scan 1 vs after scan 2."""
import csv, pathlib
here = pathlib.Path(__file__).parent
A = ["LEAKAGE_RECOVERY","COORDINATION","THROUGHPUT","WAITING_DELAY","QUALITY_ERRORS","FORECASTING","SCHEDULING","ASSET_UTILISATION","MAINTENANCE","PROCUREMENT","INVENTORY_WORKING_CAPITAL","DECISION_LATENCY","INFORMATION_FLOW","KNOWLEDGE_WORK","CUSTOMER_FLOW","WORKFORCE_PRODUCTIVITY","COMPLIANCE_ADMINISTRATION","RESOURCE_ALLOCATION"]
rows = list(csv.DictReader(open(here/"archetypes.csv")))
def cnt(rs, a): return sum(r["primary"]==a for r in rs), sum(r["secondary"]==a for r in rs)
s1 = [r for r in rows if r["scan"]=="1"]; al = rows
lines = ["| archetype | scan 1 primary | scan 1 secondary | scan 1 status | after scan 2 primary | after scan 2 secondary |","|---|---|---|---|---|---|"]
for a in A:
    p1, q1 = cnt(s1, a); p2, q2 = cnt(al, a)
    st = "ABSENT" if p1+q1==0 else ("THIN (secondary only)" if p1==0 else ("THIN" if p1==1 else "covered"))
    if a=="LEAKAGE_RECOVERY": st = f"OVER-REPRESENTED ({p1}/{len(s1)} = {p1/len(s1):.0%})"
    lines.append(f"| {a} | {p1} | {q1} | {st} | {p2} | {q2} |")
t = "\n".join(lines); print(t)
(here/"coverage_results.md").write_text("# Archetype coverage — generated by coverage.py\n\n"+t+"\n")
