"""Rubric v2 scoring: two axes (WEDGE practicality, CEILING capability) + gates.

See ../../rubric_v2.md. Selection rank = geometric mean of WEDGE and CEILING,
only for candidates that pass kills and both gates. Also re-runs the bias audit
(LEAKAGE vs all other archetypes) and a random-weight robustness test.
"""
import csv, math, random, statistics as st, pathlib
here = pathlib.Path(__file__).parent
WD = dict(WSEV=14,MEAS=14,URG=14,ACC_A=14,SOLV=12,TTP=10,SAT=10,RISK=7,IMPL=5)
CEIL_SUB = ["T","K","S","P","I","E","Z","V","A","J"]
CD = dict(CEIL=50,COMP=12,REP=10,MOAT=10,ACC_B=10,LEARN=8)
GATE_W, GATE_C = 60, 60
rows = list(csv.DictReader(open(here/"scores_v2.csv")))
num = set(WD)|set(CEIL_SUB)|set(CD)-{"CEIL"}
for r in rows:
    for k in num: r[k] = int(r[k])
    r["CEIL"] = sum(r[k] for k in CEIL_SUB)/len(CEIL_SUB)
def wedge(r, w=WD): return 100*sum(r[k]*w[k] for k in w)/(5*sum(w.values()))
def ceiling(r, w=CD): return 100*sum(r[k]*w[k] for k in w)/(5*sum(w.values()))
def combined(r, wd=WD, cd=CD): return math.sqrt(wedge(r, wd)*ceiling(r, cd))
alive = [r for r in rows if not r["kill_v2"]]
out = []; p = out.append
p(f"Candidates scored: {len(rows)}; surviving v2 kills: {len(alive)}\n")
p("## Surviving candidates (sorted by combined = sqrt(WEDGE x CEILING))\n")
p("| id | candidate | archetype | tier | conf | WEDGE | CEILING | combined | passes gates |\n|---|---|---|---|---|---|---|---|---|")
for r in sorted(alive, key=lambda r: -combined(r)):
    g = wedge(r) >= GATE_W and ceiling(r) >= GATE_C
    p(f"| {r['id']} | {r['name']} | {r['archetype']} | {r['access_tier']} | {r['confidence']} | {wedge(r):.1f} | {ceiling(r):.1f} | {combined(r):.1f} | {'yes' if g else 'no'} |")

# robustness: random weights within each axis
random.seed(11); K = 10000
top = {r["id"]:0 for r in alive}
for _ in range(K):
    wd = {k: random.expovariate(1) for k in WD}; cd = {k: random.expovariate(1) for k in CD}
    s = sorted(alive, key=lambda r: -combined(r, wd, cd))[:5]
    for r in s: top[r["id"]] += 1
p(f"\n## Robustness: share of {K} random weightings (Dirichlet(1) within each axis) in which a candidate is in the top 5\n")
for i, c in sorted(top.items(), key=lambda x: -x[1])[:12]:
    p(f"- {i}: {c/K:.0%}")

# bias re-audit on all scored rows (kills ignored, as in the v1 audit)
L = [r for r in rows if r["archetype"]=="LEAKAGE_RECOVERY"]; O = [r for r in rows if r["archetype"]!="LEAKAGE_RECOVERY"]
p(f"\n## Bias re-audit (all {len(rows)} rows, kills ignored)\n")
for name, f in (("WEDGE", wedge), ("CEILING", ceiling), ("combined", combined)):
    gl, go = st.mean(f(r) for r in L), st.mean(f(r) for r in O)
    p(f"- {name}: LEAKAGE {gl:.1f} vs OTHER {go:.1f} (gap {gl-go:+.1f})")
ml, mo = st.mean(r["MEAS"] for r in L), st.mean(r["MEAS"] for r in O)
p(f"- MEAS (re-anchored definition; scores barely moved): LEAKAGE {ml:.2f} vs OTHER {mo:.2f}")
wl = [wedge(r) for r in L]; wo = [wedge(r) for r in O]
p(f"- WEDGE-only top 5: {', '.join(r['id']+'('+r['archetype'][:4]+')' for r in sorted(alive, key=lambda r:-wedge(r))[:5])}")
(here/"results_v2.md").write_text("# Rubric v2 results — generated by score_v2.py (do not edit by hand)\n\n" + "\n".join(out) + "\n")
print("\n".join(out))
