"""Weighted rubric scoring with sensitivity analysis.

Scores are 0-5 per dimension (5 = most favourable; inverse dimensions such as
IMPL/RISK/SAT are already scored so that 5 = low cost / low risk / low saturation).
Weights come from ../opportunity_rubric.md. A candidate is only "robust" if it
stays in the top half under every weight set.
"""
import csv, pathlib

DIMS = ["SEV","FREQ","MEAS","ACC","TTP","SOLV","REP","URG","IMPL","RISK","SAT","COMP","AIL","PIND","LEARN","MOAT"]
WEIGHTS = {
    "primary":      dict(SEV=9,FREQ=6,MEAS=10,ACC=9,TTP=9,SOLV=7,REP=6,URG=9,IMPL=5,RISK=6,SAT=6,COMP=5,AIL=3,PIND=2,LEARN=4,MOAT=4),
    "equal":        {d: 1 for d in DIMS},
    "value_heavy":  dict(SEV=16,FREQ=6,MEAS=8,ACC=6,TTP=5,SOLV=7,REP=8,URG=12,IMPL=3,RISK=5,SAT=6,COMP=6,AIL=2,PIND=1,LEARN=2,MOAT=7),
    "speed_heavy":  dict(SEV=6,FREQ=6,MEAS=12,ACC=13,TTP=14,SOLV=7,REP=5,URG=8,IMPL=7,RISK=6,SAT=4,COMP=3,AIL=2,PIND=2,LEARN=3,MOAT=1),
    "defensibility":dict(SEV=8,FREQ=5,MEAS=8,ACC=7,TTP=6,SOLV=6,REP=6,URG=8,IMPL=4,RISK=5,SAT=10,COMP=9,AIL=2,PIND=3,LEARN=3,MOAT=10),
}

here = pathlib.Path(__file__).parent
rows = list(csv.DictReader(open(here / "scores.csv")))

def score(r, w):
    return 100 * sum(int(r[d]) * w[d] for d in DIMS) / (5 * sum(w.values()))

out = []
ranks = {}
for name, w in WEIGHTS.items():
    s = sorted(rows, key=lambda r: -score(r, w))
    ranks[name] = {r["id"]: i + 1 for i, r in enumerate(s)}

half = len(rows) / 2
lines = ["| id | candidate | conf | " + " | ".join(WEIGHTS) + " | worst rank | robust |",
         "|---|---|---|" + "---|" * len(WEIGHTS) + "---|---|"]
for r in sorted(rows, key=lambda r: -score(r, WEIGHTS["primary"])):
    cells = [f"{score(r, w):.1f} (#{ranks[n][r['id']]})" for n, w in WEIGHTS.items()]
    worst = max(ranks[n][r["id"]] for n in WEIGHTS)
    lines.append(f"| {r['id']} | {r['name']} | {r['confidence']} | " + " | ".join(cells) + f" | {worst} | {'yes' if worst <= half else 'no'} |")
table = "\n".join(lines)
(here / "results.md").write_text(
    "# Rubric results (generated by score.py — do not edit by hand)\n\n"
    "Score = weighted mean of 0-5 dimension scores, scaled to 0-100. Rank in brackets.\n"
    "Robust = stays in the top half under every weight set.\n"
    "Confidence: H/M/L = evidence confidence behind the scores (see candidate_ledger.csv).\n\n"
    + table + "\n")
print(table)
